### ISSUE TITLE
please share getting started guide

### ISSUE THREAD

**Issue by faraazc** [Akirato/Twitter-Sentiment-Analysis-Tool#1]
Thanks for sharing your Twitter sentiment analyser tool on Github. It looks awesome

I would like to experiment with your tool.

which script to run to train the model?
where sentiment140 present?
which is the starting point ?

I have looked in to github() repo. i could see some information in README. But could not get started with those info.

Can you please a sequence of commands in need to execute.
i mean like which script to run first and in sequence.

Also can you list of dependencies i need to install before getting started.

**Comment by Akirato** [comment]
@faraazc 
You can take sentiment140 data from here [https://docs.google.com/file/d/0B04GJPshIjmPRnZManQwWEdTZjg/edit](https://docs.google.com/file/d/0B04GJPshIjmPRnZManQwWEdTZjg/edit)

Pre-process this file according to your needs and store at Data/sentences.cleaned.abbreviated
Then:
1. `python make_word2vec_model.py` - This is to make a word2vec model
2. `python vectorize.py en <your-file>` - This is to make vectors of words in your file - This will make a pickle file with vectors in it  of the name <your-file>.word.vectors.en - 'en' is in case you are doing it for english. You can use other tags as well.
3. `python train_and_validate.py` - This is to train a lot of classifiers: Random Forest, Decision Trees, Gaussian Naive Bayes, Logistic Regression, svm, Multi-Layer Perceptron - This will take several minutes depending on your system. Your system might get stuck, but its worth it :smiley:
The program will also give you accuracies.
4. `python get_sentiment_word.py` - GUI to input sentences to get output - You will need to install `easygui` using `pip install easygui`

**Comment by faraazc** [comment]
@Akirato Thank you. This helped.

**Comment by rxng** [comment]
Hi, 

"Pre-process this file according to your needs and store at Data/sentences.cleaned.abbreviated"

How do we preprocess it?

Thank you!

**Comment by Akirato** [comment]
For starters, you can use the `preprocessing.py` file.
But the preprocessing includes tokenization, detecting abbreviations and other such things.
So, you can do it according to you too.
Preprocessed data goes into Data/sentences.cleaned.abbreviated

**Comment by rxng** [comment]
Hi thank you so much! I have tried but this keeps appearing:

> 2017-04-10 14:52:26,487 : INFO : loading Word2Vec object from model.en
> 2017-04-10 14:52:26,786 : INFO : loading wv recursively from model.en.wv.* with mmap=None
> 2017-04-10 14:52:26,786 : INFO : setting ignored attribute syn0norm to None
> 2017-04-10 14:52:26,786 : INFO : setting ignored attribute cum_table to None
> 2017-04-10 14:52:26,786 : INFO : loaded model.en
> The model is loaded.
> Traceback (most recent call last):
>   File "vectorize.py", line 31, in <module>
>     vectorize(lang_tag,filename)
>   File "vectorize.py", line 11, in vectorize
>     data = data_file.read()
>   File "/Users/rxng/.pyenv/versions/scientific/lib/python2.7/codecs.py", line 686, in read
>     return self.reader.read(size)
>   File "/Users/rxng/.pyenv/versions/scientific/lib/python2.7/codecs.py", line 492, in read
>     newchars, decodedbytes = self.decode(data, self.errors)
> UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 0: invalid start byte
> (scientific) ~/D/g/Twitter-Sentiment-Analysis-Tool ❯❯❯ python vectorize.py en model.en

**Comment by Akirato** [comment]
Is your file in unicode(utf-8) format. If you are using linux-based system:
`file <file-name>` 
If you are not using a unicode(utf-8), you can use `iconv` or some tool similar to it
